// Package models contains the types for schema.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"fmt"
	"strings"

	"github.com/pkg/errors"
)

// InsertBook inserts the Book to the database.
func (s *PostgresStorage) InsertBook(db XODB, b *Book) error {
	var err error

	// if already exist, bail
	if b._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	const sqlstr = `INSERT INTO public.books (` +
		`author_id, isbn, booktype, title, year, available, tags, width, length` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`) RETURNING book_id`

	// run query
	s.info(sqlstr, b.AuthorID, b.Isbn, b.Booktype, b.Title, b.Year, b.Available, b.Tags, b.Width, b.Length)
	err = db.QueryRow(sqlstr, b.AuthorID, b.Isbn, b.Booktype, b.Title, b.Year, b.Available, b.Tags, b.Width, b.Length).Scan(&b.BookID)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// InsertBookByFields inserts the Book to the database.
func (s *PostgresStorage) InsertBookByFields(db XODB, b *Book) error {
	var err error

	params := make([]interface{}, 0, 9)
	fields := make([]string, 0, 9)
	retCols := `book_id`
	retVars := make([]interface{}, 0, 9)
	retVars = append(retVars, &b.BookID)
	fields = append(fields, `author_id`)
	params = append(params, b.AuthorID)

	fields = append(fields, `isbn`)
	params = append(params, b.Isbn)

	fields = append(fields, `booktype`)
	params = append(params, b.Booktype)

	fields = append(fields, `title`)
	params = append(params, b.Title)

	fields = append(fields, `year`)
	params = append(params, b.Year)

	fields = append(fields, `available`)
	params = append(params, b.Available)

	fields = append(fields, `tags`)
	params = append(params, b.Tags)

	fields = append(fields, `width`)
	params = append(params, b.Width)
	if b.Length.Valid {
		fields = append(fields, `length`)
		params = append(params, b.Length)
	} else {
		retCols += `, length`
		retVars = append(retVars, &b.Length)
	}
	if len(params) == 0 {
		// FIXME(jackie): maybe we should allow this?
		return errors.New("all fields are empty, unable to insert")
	}

	var placeHolders []string
	var placeHolderVals []interface{}
	for i := range params {
		placeHolders = append(placeHolders, "$%d")
		placeHolderVals = append(placeHolderVals, i+1)
	}
	placeHolderStr := fmt.Sprintf(strings.Join(placeHolders, ","), placeHolderVals...)

	sqlstr := `INSERT INTO public.books (` +
		strings.Join(fields, ",") +
		`) VALUES (` + placeHolderStr +
		`) RETURNING ` + retCols

	s.info(sqlstr, params)
	err = db.QueryRow(sqlstr, params...).Scan(retVars...)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// UpdateBook updates the Book in the database.
func (s *PostgresStorage) UpdateBook(db XODB, b *Book) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if b._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query

	const sqlstr = `UPDATE public.books SET (` +
		`author_id, isbn, booktype, title, year, available, tags, width, length` +
		`) = ( ` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`) WHERE book_id = $10`

	// run query
	s.info(sqlstr, b.AuthorID, b.Isbn, b.Booktype, b.Title, b.Year, b.Available, b.Tags, b.Width, b.Length, b.BookID)
	_, err = db.Exec(sqlstr, b.AuthorID, b.Isbn, b.Booktype, b.Title, b.Year, b.Available, b.Tags, b.Width, b.Length, b.BookID)
	return err
}

// UpdateBookByFields updates the Book in the database.
func (s *PostgresStorage) UpdateBookByFields(db XODB, b *Book, fields, retCols []string, params, retVars []interface{}) error {
	var placeHolders []string
	var idxvals []interface{}
	for i := range params {
		placeHolders = append(placeHolders, "$%d")
		idxvals = append(idxvals, i+1)
	}
	params = append(params, b.BookID)
	idxvals = append(idxvals, len(params))

	var sqlstr string
	if len(fields) == 1 {
		sqlstr = fmt.Sprintf(`UPDATE public.books SET `+
			strings.Join(fields, ",")+
			` = `+strings.Join(placeHolders, ",")+
			` WHERE id = $%d`+
			` RETURNING `+strings.Join(retCols, ", "), idxvals...)
	} else {
		sqlstr = fmt.Sprintf(`UPDATE public.books SET (`+
			strings.Join(fields, ",")+
			`) = (`+strings.Join(placeHolders, ",")+
			`) WHERE book_id = $%d`+
			` RETURNING `+strings.Join(retCols, ", "), idxvals...)
	}
	s.info(sqlstr, params)
	if err := db.QueryRow(sqlstr, params...).Scan(retVars...); err != nil {
		return err
	}

	return nil
}

// SaveBook saves the Book to the database.
func (s *PostgresStorage) SaveBook(db XODB, b *Book) error {
	if b.Exists() {
		return s.UpdateBook(db, b)
	}

	return s.InsertBook(db, b)
}

// UpsertBook performs an upsert for Book.
func (s *PostgresStorage) UpsertBook(db XODB, b *Book) error {
	var err error

	// sql query
	const sqlstr = `INSERT INTO public.books (` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10` +
		`) ON CONFLICT (book_id) DO UPDATE SET (` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length` +
		`) = (` +
		`EXCLUDED.book_id, EXCLUDED.author_id, EXCLUDED.isbn, EXCLUDED.booktype, EXCLUDED.title, EXCLUDED.year, EXCLUDED.available, EXCLUDED.tags, EXCLUDED.width, EXCLUDED.length` +
		`)`

	// run query
	s.info(sqlstr, b.BookID, b.AuthorID, b.Isbn, b.Booktype, b.Title, b.Year, b.Available, b.Tags, b.Width, b.Length)
	_, err = db.Exec(sqlstr, b.BookID, b.AuthorID, b.Isbn, b.Booktype, b.Title, b.Year, b.Available, b.Tags, b.Width, b.Length)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// DeleteBook deletes the Book from the database.
func (s *PostgresStorage) DeleteBook(db XODB, b *Book) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return nil
	}

	// if deleted, bail
	if b._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.books WHERE book_id = $1`

	// run query
	s.info(sqlstr, b.BookID)
	_, err = db.Exec(sqlstr, b.BookID)
	if err != nil {
		return err
	}

	// set deleted
	b._deleted = true

	return nil
}

// DeleteBooks deletes the Book from the database.
func (s *PostgresStorage) DeleteBooks(db XODB, bs []*Book) error {
	var err error

	if len(bs) == 0 {
		return nil
	}

	var args []interface{}
	var placeholder string
	for i, b := range bs {
		args = append(args, b.BookID)
		if i != 0 {
			placeholder = placeholder + ", "
		}
		placeholder += fmt.Sprintf("$%d", i+1)
	}

	// sql query
	var sqlstr = `DELETE FROM public.books WHERE book_id in (` + placeholder + `)`

	// run query
	s.info(sqlstr, args)
	_, err = db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	// set deleted
	for _, b := range bs {
		b._deleted = true
	}

	return nil
}

// GetMostRecentBook returns n most recent rows from 'books',
// ordered by "created_date" in descending order.
func (s *PostgresStorage) GetMostRecentBook(db XODB, n int) ([]*Book, error) {
	const sqlstr = `SELECT ` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length ` +
		`FROM public.books ` +
		`ORDER BY created_date DESC LIMIT $1`

	s.info(sqlstr, n)
	q, err := db.Query(sqlstr, n)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Book
	for q.Next() {
		b := Book{}

		// scan
		err = q.Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
}

// GetMostRecentChangedBook returns n most recent rows from 'books',
// ordered by "changed_date" in descending order.
func (s *PostgresStorage) GetMostRecentChangedBook(db XODB, n int) ([]*Book, error) {
	const sqlstr = `SELECT ` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length ` +
		`FROM public.books ` +
		`ORDER BY changed_date DESC LIMIT $1`

	s.info(sqlstr, n)
	q, err := db.Query(sqlstr, n)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Book
	for q.Next() {
		b := Book{}

		// scan
		err = q.Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
}

// GetAllBook returns all rows from 'books', based on the BookQueryArguments.
// If the BookQueryArguments is nil, it will use the default BookQueryArguments instead.
func (s *PostgresStorage) GetAllBook(db XODB, queryArgs *BookQueryArguments) ([]*Book, error) { // nolint: gocyclo
	queryArgs = ApplyBookQueryArgsDefaults(queryArgs)
	if queryArgs.filterArgs == nil {
		filterArgs, err := getBookFilter(queryArgs.Where)
		if err != nil {
			return nil, errors.Wrap(err, "unable to get Book filter")
		}
		queryArgs.filterArgs = filterArgs
	}

	desc := ""
	if *queryArgs.Desc {
		desc = "DESC"
	}

	dead := "NULL"
	if *queryArgs.Dead {
		dead = "NOT NULL"
	}

	orderBy := "book_id"
	foundIndex := false
	dbFields := map[string]bool{
		"book_id":   true,
		"author_id": true,
		"isbn":      true,
		"booktype":  true,
		"title":     true,
		"year":      true,
		"available": true,
		"tags":      true,
		"width":     true,
		"length":    true,
	}

	if *queryArgs.OrderBy != "" && *queryArgs.OrderBy != defaultOrderBy {
		foundIndex = dbFields[*queryArgs.OrderBy]
		if !foundIndex {
			return nil, fmt.Errorf("unable to order by %s, field not found", *queryArgs.OrderBy)
		}
		orderBy = *queryArgs.OrderBy
	}

	var params []interface{}
	placeHolders := ""
	if queryArgs.filterArgs != nil {
		pls := make([]string, len(queryArgs.filterArgs.filterPairs))
		for i, pair := range queryArgs.filterArgs.filterPairs {
			pls[i] = fmt.Sprintf("%s %s $%d", pair.fieldName, pair.option, i+1)
			params = append(params, pair.value)
		}
		placeHolders = strings.Join(pls, " "+queryArgs.filterArgs.conjunction+" ")
		placeHolders = fmt.Sprintf("(%s) AND", placeHolders)
	}
	params = append(params, *queryArgs.Offset)
	offsetPos := len(params)

	params = append(params, *queryArgs.Limit)
	limitPos := len(params)

	var sqlstr = fmt.Sprintf(`SELECT %s FROM %s WHERE %s deleted_date IS %s ORDER BY %s %s OFFSET $%d LIMIT $%d`,
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length `,
		`public.books`,
		placeHolders,
		dead,
		orderBy,
		desc,
		offsetPos,
		limitPos)
	s.info(sqlstr, params)

	q, err := db.Query(sqlstr, params...)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Book
	for q.Next() {
		b := Book{}

		// scan
		err = q.Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
}

// CountAllBook returns a count of all rows from 'books'
func (s *PostgresStorage) CountAllBook(db XODB, queryArgs *BookQueryArguments) (int, error) {
	queryArgs = ApplyBookQueryArgsDefaults(queryArgs)
	if queryArgs.filterArgs == nil {
		filterArgs, err := getBookFilter(queryArgs.Where)
		if err != nil {
			return 0, errors.Wrap(err, "unable to get Book filter")
		}
		queryArgs.filterArgs = filterArgs
	}

	dead := "NULL"
	if *queryArgs.Dead {
		dead = "NOT NULL"
	}

	var params []interface{}
	placeHolders := ""
	if queryArgs.filterArgs != nil {
		pls := make([]string, len(queryArgs.filterArgs.filterPairs))
		for i, pair := range queryArgs.filterArgs.filterPairs {
			pls[i] = fmt.Sprintf("%s %s $%d", pair.fieldName, pair.option, i+1)
			params = append(params, pair.value)
		}
		placeHolders = strings.Join(pls, " "+queryArgs.filterArgs.conjunction+" ")
		placeHolders = fmt.Sprintf("(%s) AND", placeHolders)
	}

	var err error
	var sqlstr = fmt.Sprintf(`SELECT count(*) from public.books WHERE %s deleted_date IS %s`, placeHolders, dead)
	s.info(sqlstr)

	var count int
	err = db.QueryRow(sqlstr, params...).Scan(&count)
	if err != nil {
		return -1, err
	}
	return count, nil
}

// BooksByAuthorIDFK retrieves rows from public.books by foreign key AuthorID.
// Generated from foreign key Author.
func (s *PostgresStorage) BooksByAuthorIDFK(db XODB, authorID int, queryArgs *BookQueryArguments) ([]*Book, error) {
	queryArgs = ApplyBookQueryArgsDefaults(queryArgs)

	desc := ""
	if *queryArgs.Desc {
		desc = "DESC"
	}

	dead := "NULL"
	if *queryArgs.Dead {
		dead = "NOT NULL"
	}

	var params []interface{}
	placeHolders := ""
	if queryArgs.filterArgs != nil {
		pos := 0
		pls := make([]string, 0, len(queryArgs.filterArgs.filterPairs))
		for _, pair := range queryArgs.filterArgs.filterPairs {
			if pair.fieldName == "author_id" {
				return nil, fmt.Errorf("already have condition on field:AuthorID, because of foregin key Author")
			}
			pos++
			pls = append(pls, fmt.Sprintf("%s %s $%d", pair.fieldName, pair.option, pos))
			params = append(params, pair.value)
		}
		placeHolders = strings.Join(pls, " "+queryArgs.filterArgs.conjunction+" ")
		placeHolders = fmt.Sprintf("(%s) AND", placeHolders)
	}
	params = append(params, authorID)
	placeHolders = fmt.Sprintf(`%s author_id = $%d AND `, placeHolders, len(params))

	params = append(params, *queryArgs.Offset)
	offsetPos := len(params)

	params = append(params, *queryArgs.Limit)
	limitPos := len(params)

	var sqlstr = fmt.Sprintf(
		`SELECT %s FROM %s WHERE %s deleted_date IS %s ORDER BY %s %s OFFSET $%d LIMIT $%d`,
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length `,
		`public.books`,
		placeHolders,
		dead,
		"book_id",
		desc,
		offsetPos,
		limitPos)

	s.info(sqlstr, params...)
	q, err := db.Query(sqlstr, params...)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Book
	for q.Next() {
		b := Book{}

		// scan
		err = q.Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
}

// CountBooksByAuthorIDFK count rows from public.books by foreign key AuthorID.
// Generated from foreign key Author.
func (s *PostgresStorage) CountBooksByAuthorIDFK(db XODB, authorID int, queryArgs *BookQueryArguments) (int, error) {
	queryArgs = ApplyBookQueryArgsDefaults(queryArgs)

	dead := "NULL"
	if *queryArgs.Dead {
		dead = "NOT NULL"
	}

	var params []interface{}
	placeHolders := ""
	if queryArgs.filterArgs != nil {
		pos := 0
		pls := make([]string, 0, len(queryArgs.filterArgs.filterPairs))
		for _, pair := range queryArgs.filterArgs.filterPairs {
			if pair.fieldName == "author_id" {
				return -1, fmt.Errorf("already have condition on field:AuthorID, because of foregin key Author")
			}
			pos++
			pls = append(pls, fmt.Sprintf("%s %s $%d", pair.fieldName, pair.option, pos))
			params = append(params, pair.value)
		}
		placeHolders = strings.Join(pls, " "+queryArgs.filterArgs.conjunction+" ")
		placeHolders = fmt.Sprintf("(%s) AND", placeHolders)
	}
	params = append(params, authorID)
	placeHolders = fmt.Sprintf(`%s author_id = $%d AND `, placeHolders, len(params))

	var err error
	var sqlstr = fmt.Sprintf(`SELECT count(*) from public.books WHERE %s deleted_date IS %s`, placeHolders, dead)
	s.info(sqlstr)

	var count int
	err = db.QueryRow(sqlstr, params...).Scan(&count)
	if err != nil {
		return -1, err
	}
	return count, nil
}

// AuthorInBook returns the Author associated with the Book's AuthorID (author_id).
//
// Generated from foreign key 'books_author_id_fkey'.
func (s *PostgresStorage) AuthorInBook(db XODB, b *Book) (*Author, error) {
	return s.AuthorByAuthorID(db, b.AuthorID)
}

// BookByIsbn retrieves a row from 'public.books' as a Book.
//
// Generated from index 'books_isbn_key'.
func (s *PostgresStorage) BookByIsbn(db XODB, isbn string) (*Book, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length ` +
		`FROM public.books ` +
		`WHERE isbn = $1`

	// run query
	s.info(sqlstr, isbn)
	b := Book{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, isbn).Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
	if err != nil {
		return nil, err
	}

	return &b, nil
}

// BookByBookID retrieves a row from 'public.books' as a Book.
//
// Generated from index 'books_pkey'.
func (s *PostgresStorage) BookByBookID(db XODB, bookID int) (*Book, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length ` +
		`FROM public.books ` +
		`WHERE book_id = $1`

	// run query
	s.info(sqlstr, bookID)
	b := Book{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, bookID).Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
	if err != nil {
		return nil, err
	}

	return &b, nil
}

// BooksByTitle retrieves a row from 'public.books' as a Book.
//
// Generated from index 'books_title_idx'.
func (s *PostgresStorage) BooksByTitle(db XODB, title string, year int) ([]*Book, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length ` +
		`FROM public.books ` +
		`WHERE title = $1 AND year = $2`

	// run query
	s.info(sqlstr, title, year)
	q, err := db.Query(sqlstr, title, year)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Book{}
	for q.Next() {
		b := Book{
			_exists: true,
		}

		// scan
		err = q.Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
}

// BooksByTitleLower retrieves a row from 'public.books' as a Book.
//
// Generated from index 'books_title_lower_idx'.
func (s *PostgresStorage) BooksByTitleLower(db XODB, title string) ([]*Book, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`book_id, author_id, isbn, booktype, title, year, available, tags, width, length ` +
		`FROM public.books ` +
		`WHERE title = $1`

	// run query
	s.info(sqlstr, title)
	q, err := db.Query(sqlstr, title)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Book{}
	for q.Next() {
		b := Book{
			_exists: true,
		}

		// scan
		err = q.Scan(&b.BookID, &b.AuthorID, &b.Isbn, &b.Booktype, &b.Title, &b.Year, &b.Available, &b.Tags, &b.Width, &b.Length)
		if err != nil {
			return nil, err
		}

		res = append(res, &b)
	}

	return res, nil
}
